# basic options
title: 82r Frozen In Time
author: r3d bullion
email: r3d@redbullion.com
description: resources for Frozen In Time
twitter_username: rrtUK-tbd
github_username:  rrtUK

# Build settings
markdown: kramdown
theme: minima
